# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Andrew's Blog
tagline:          'Andrew Blog'
description:      'A place for documenting my research and study'
url:              http://andrewccchan.github.io
baseurl:          /

author:
  name:           'Chin-Cheng Chan'

plugins: [jekyll-paginate]

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/andrewccchan
