# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Chin-Cheng Chan's Homepage
tagline:          'Homepage'
description:      'A place for documenting my research'
url:              http://andrewccchan.github.io
baseurl:          /

author:
  name:           'Chin-Cheng Chan'

plugins: [jekyll-paginate]

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/andrewccchan
